### PR TITLE
Use mechanism to control Callback subscriptions

### PR DESCRIPTION
**Pull request by andreparames**
There are some minor changes, but the main thing is using the new CallbackSubscription feature introduced in https://github.com/MOV-AI/data-access-layer/pull/222, plus the unit test that confirms that the Callbacks no longer work after a transition is initiated.

Part of [BP-944](https://movai.atlassian.net/browse/BP-944)

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[BP-944]: https://movai.atlassian.net/browse/BP-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: gd_node/node.py [hunk 1]
```diff
@@ -257,19 +276,16 @@ async def init_iports(
                 }
                 if (key in [MOVAI_INIT,MOVAI_TRANSITION]) == init:
                     port_instance = Iport.create(key, **config)
-                    if key == MOVAI_CONTEXTCLIENTIN:
```
Comment (duartecoelhomovai) [inline gd_node/node.py:260]: We were just ensuring the ports of contextclientin because they are the only ones that wait on redis key, which were subscribing to that SubscribeManager (old one).
Are you sure the other ports types are also changing their status to ready ?

File: gd_node/node.py [hunk 2]
```diff
@@ -367,6 +383,6 @@ async def main(self, args, unknown) -> None:
 
         signal.signal(signal.SIGINT, CoreInterruptHandler)
         signal.signal(signal.SIGTERM, CoreInterruptHandler)
-        await type(self).RUNNING.wait()
+        await type(self).STOPPING_EVENT.wait()
```
Comment (duartecoelhomovai) [inline gd_node/node.py:386]: Isn't this function the initialization of a node?  Might be confusing to see "stopping" but maybe i didnt understand it correctly :D

File: gd_node/protocol.py [hunk 3]
```diff
@@ -174,10 +175,8 @@ def shutdown(self):
         # disable all callback events
         self._callbacks.clear()
         for instance in self._instances:
-            try:
+            if hasattr(instance, "shutdown"):
```
Comment (duartecoelhomovai) [inline gd_node/protocol.py:178]: if i understand correctly, the has attr is checking if instance has the attribute shutdown. In the next line you are calling the function shutdown. Didn't you mean to check if it has the shutdown function and not the attribute? (might be me without context)

**Review by duartecoelhomovai — COMMENTED** [review]
Please review the comments

**Comment by duartecoelhomovai** [comment]
Will try to run today the test and vicentes context issue replication test also on a robot to further help you validate this

File: gd_node/protocol.py (hunk 3 above)
Comment (andreparames) [reply gd_node/protocol.py:178]: A method is an attribute in Python :) basically it's checking if the method exists (not all ports need a shutdown method).

**Review by diasdm — CHANGES_REQUESTED** [review]
After installing I'm getting the following:
```
  File "/usr/local/lib/python3.8/dist-packages/gd_node/protocols/ros1.py", line 130, in callback
    if self._gd_node.RUNNING and self.enabled:
AttributeError: 'GDNode' object has no attribute 'RUNNING'
```

File: gd_node/node.py (hunk 1 above)
Comment (andreparames) [reply gd_node/node.py:260]: Only ports with a ready() method will be awaited on, and I've only added the ready() method to the Context ports, so other ports are unaffected.

**Comment by andreparames** [comment]
Build is broken because it needs then changes made in https://github.com/MOV-AI/data-access-layer/pull/222, which should be merged before.

File: gd_node/protocol.py [hunk 4]
```diff
@@ -328,6 +330,9 @@ def __init__(self, **kwargs):
         self._instance = MovAI.ContextServerIn(**kwargs)
         gd.iport[name] = self._instance
 
+    async def ready(self) -> Event:
```
Comment (diasdm) [inline gd_node/protocol.py:333]: Is a shutdown required for the server?

File: gd_node/protocols/base.py [hunk 5]
```diff
@@ -10,10 +10,13 @@
    Base classes for all protocols
 """
 
-from typing import Any
+from typing import TYPE_CHECKING, Any
 
 from gd_node.callback import GD_Callback as Callback
 
+if TYPE_CHECKING:
```
Comment (diasdm) [inline gd_node/protocols/base.py:17]: Nice :)

File: tests/test_suite.py [hunk 6]
```diff
@@ -1,9 +1,118 @@
...
+
+@patch("gd_node.node.signal.signal", new=MagicMock)
 class TestSuite(unittest.TestCase):
-    def test_handler_executer_forward(self):
-        assert True
+
+    @fake_redis("dal.movaidb.database.Connection", recording_dir=test_dir)
+    @fake_redis("dal.plugins.persistence.redis.redis.Connection", recording_dir=test_dir)
+    @patch("dal.movaidb.database.aioredis.ConnectionsPool", FakeAsyncPool)
+    def test_disable_callbacks_on_transition(self):
```
Comment (diasdm) [inline tests/test_suite.py:18]: Clarify test steps pls

**Review by diasdm — CHANGES_REQUESTED** [review]
When installing dal 9887c89b14f5432d789df54417852d5b366cec3a and gd-node a4ea464ae975b5f7924e1eb78718620f3eb63bef on top of EE 2.4.1-77 and Tugbot 2.4.3-26 I got the following exception:
```
[INFO][2024-05-16 14:25:40][spawner_core][SpawnerCore.register_sub][161]: [user_log:True] Subscribing to key: Robot:4f4875cb5e254da2b43e4194e75addbd,Actions: - conn_local - conn_local_sub
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dal/models/message.py", line 201, in export_portdata
    ports_data = System('PortsData', db=db) #db_scopes.System['PortsData']
  File "/usr/local/lib/python3.8/dist-packages/dal/scopes/system.py", line 21, in __init__
    super().__init__(scope="System", name=name, version=version, new=new, db=db)
  File "/usr/local/lib/python3.8/dist-packages/dal/scopes/scope.py", line 28, in __init__
    template_struct = MovaiDB.API(url=SCHEMA_FOLDER_PATH)[scope]
  File "/usr/local/lib/python3.8/dist-packages/dal/movaidb/database.py", line 260, in __init__
    for schema_file in Resource.list_resources(current_path)
  File "/usr/local/lib/python3.8/dist-packages/dal/plugins/classes/resource.py", line 134, in list_resources
    return Resource.get_plugin(url).list_resources(url, recursive)
  File "/usr/local/lib/python3.8/dist-packages/dal/plugins/resources/file/file.py", line 109, in list_resources
    local_path = self._get_local_path(url)
  File "/usr/local/lib/python3.8/dist-packages/dal/plugins/resources/file/file.py", line 150, in _get_local_path
    raise ValueError("Can't open url: {}".format(url))
ValueError: Can't open url: file://usr/local/lib/python3.8/dist-packages/dal/validation/schema/1.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/init_local_db", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/flow_initiator/tools/init_local_db.py", line 21, in main
    Message.export_portdata(db="local")
  File "/usr/local/lib/python3.8/dist-packages/dal/models/message.py", line 203, in export_portdata
    ports_data = System('PortsData', new=True, db=db) # db_scopes.create('System', 'PortsData')
  File "/usr/local/lib/python3.8/dist-packages/dal/scopes/system.py", line 21, in __init__
    super().__init__(scope="System", name=name, version=version, new=new, db=db)
  File "/usr/local/lib/python3.8/dist-packages/dal/scopes/scope.py", line 28, in __init__
    template_struct = MovaiDB.API(url=SCHEMA_FOLDER_PATH)[scope]
  File "/usr/local/lib/python3.8/dist-packages/dal/movaidb/database.py", line 260, in __init__
    for schema_file in Resource.list_resources(current_path)
  File "/usr/local/lib/python3.8/dist-packages/dal/plugins/classes/resource.py", line 134, in list_resources
    return Resource.get_plugin(url).list_resources(url, recursive)
  File "/usr/local/lib/python3.8/dist-packages/dal/plugins/resources/file/file.py", line 109, in list_resources
    local_path = self._get_local_path(url)
  File "/usr/local/lib/python3.8/dist-packages/dal/plugins/resources/file/file.py", line 150, in _get_local_path
    raise ValueError("Can't open url: {}".format(url))
ValueError: Can't open url: file://usr/local/lib/python3.8/dist-packages/dal/validation/schema/1.0
[INFO][2024-05-16 14:25:42][core][signal_shutdown][560]: signal_shutdown [atexit]
```

**Comment by andreparames** [comment]
> When installing dal 9887c89b14f5432d789df54417852d5b366cec3a and gd-node [a4ea464](https://github.com/MOV-AI/gd-node/commit/a4ea464ae975b5f7924e1eb78718620f3eb63bef) on top of EE 2.4.1-77 and Tugbot 2.4.3-26 I got the following exception:

This error is due to a bug in the init_local_db tool, which depended on a side-effect of loading SecretKey; since the DAL PR changes that side-effect, it breaks the tool. I've opened a PR to fix it properly: https://github.com/MOV-AI/flow-initiator/pull/145

File: gd_node/node.py [hunk 7]
```diff
@@ -69,11 +83,12 @@ def __init__(self, args, unknown):
         }
         self.launched_transports = []
         self.ports_params = {}
+        self.loop.set_debug(True)
```
[the remark this answers is not in the document]
Comment (andreparames) [reply gd_node/node.py]: Yes, thanks!

File: gd_node/protocol.py (hunk 4 above)
Comment (andreparames) [reply gd_node/protocol.py:333]: Yes, I think it's best we add it, thank you for pointing it out!

**Review by diasdm — CHANGES_REQUESTED** [review]
There's an exception on run time:
```
[INFO][2024-05-23 10:50:09][align_with_cart][AlignWithCart.sequence_loop][337]: [ui:True|user_log:True|node:pick__align_with_cart|callback:align_with_cart] Cart engagement successful.
[ERROR][2024-05-23 10:50:09][callback][start][146]: [node:pick__align_with_cart|callback:portname_to_function] no running event loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gd_node/callback.py", line 134, in start
    exec(code, globais)
  File "portname_to_function", line 2, in <module>
  File "align_with_cart", line 340, in sequence_loop
  File "/usr/local/lib/python3.8/dist-packages/gd_node/protocols/movai.py", line 229, in send
    GD_User.iport[iport].unregister()
  File "/usr/local/lib/python3.8/dist-packages/gd_node/protocols/movai.py", line 298, in unregister
    self.callback_subscription.unsubscribe()
  File "/usr/local/lib/python3.8/dist-packages/dal/movaidb/database.py", line 80, in unsubscribe
    self.conn.punsubscribe(self.channel)
  File "/usr/local/lib/python3.8/dist-packages/aioredis/commands/pubsub.py", line 63, in punsubscribe
    return conn.execute_pubsub(b'PUNSUBSCRIBE', pattern, *patterns)
  File "/usr/local/lib/python3.8/dist-packages/aioredis/connection.py", line 382, in execute_pubsub
    fut = get_event_loop().create_future()
RuntimeError: no running event loop
[INFO][2024-05-23 10:50:09][align_with_cart][AlignWithCart.log_on_step][110]: [user_log:True|node:pick__align_with_cart|callback:align_with_cart] 

```

**Comment by andreparames** [comment]
Other changes made to the code resolved the underlying issue. Since we haven't had issue with this area of the code since, this change is no longer relevant.
